main: com.spaceman.tport.Main
version: '${project.version}'
name: '${project.artifactId}'
author: '${author}'
api-version: '1.17'
website: '${bukkitURL}'
softdepend: [dynmap, bluemap, CrazyAdvancementsAPI]
description: "The visual location manager and other teleport related functions"

supportedVersions: [${supportedVersions}]