main: com.spaceman.tport.Main
version: '${project.version}'
name: '${project.artifactId}'
author: '${author}'
api-version: '1.17'
website: '${url}'
softdepend: [dynmap]

supportedVersions: [${supportedVersions}]