TPortTPCooldown: 3000           # cooldown of teleporting to a TPort
BackCooldown: TPortTPCooldown   # cooldown of teleporting back
PlayerTPCooldown: 3000          # cooldown of teleporting to a player
FeatureTPCooldown: 3000         # cooldown of teleporting to a feature
BiomeTPCooldown: 3000           # cooldown of teleporting to a biome

# each number is in milliseconds. 3000ms is 3 seconds.
# you can use another cooldown to link each other. Just use another cooldown
# you also can use permissions as a cooldown value to create a custom cooldown value for each player/group. to use set the value to 'permission'. The permission is then 'TPort.<cooldown>.X' where 'X' is the cooldown time and the <cooldown> is the cooldown