cooldown:
  TPortTP: 3000           # cooldown of teleporting to a TPort
  Back: TPortTP           # cooldown of teleporting back
  PlayerTP: 3000          # cooldown of teleporting to a player
  FeatureTP: 3000         # cooldown of teleporting to a feature
  BiomeTP: 3000           # cooldown of teleporting to a biome
  Search: 10000           # cooldown of searching for TPorts
Permissions:
  enabled: false
public:
  enabled: true
delay:
  permission: false
restriction:
  permission: false
biomeTP:
  searches: 100

# each number for cooldown is in milliseconds. 3000ms is 3 seconds.
# you can use another cooldown to link each other. Just use another cooldown name
# you also can use permissions as a cooldown value to create a custom cooldown value for each player/group. to use set the value to 'permission'. The permission is then 'TPort.<cooldown>.X' where 'X' is the cooldown time and the <cooldown> is the cooldown