on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#      - name: setup java 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#      - name: compile TPort without adapters
#        run: mvn -f .\tport\pom.xml clean compile
#      - name: compile and execute texture pack generator
#        run: mvn -f .\texture_generator\pom.xml clean compile exec:java

      - name: zip packs
        run: |
          cd 'resource pack/src (16x)_dark'
          zip -r TPort_16x_dark.zip .
          cd '../src (32x)_dark'
          zip -r TPort_32x_dark.zip .
          cd '../src (16x)_light'
          zip -r TPort_16x_light.zip .
          cd '../src (32x)_light'
          zip -r TPort_32x_light.zip .
          cd '../../'
      - uses: softprops/action-gh-release@v1
        with:
          files: | 
            resource pack/src (16x)_dark/TPort_16x_dark.zip
            resource pack/src (32x)_dark/TPort_32x_dark.zip
            resource pack/src (16x)_light/TPort_16x_light.zip
            resource pack/src (32x)_light/TPort_32x_light.zip
